### ISSUE TITLE
Unity Game View Different With HeadSet View

### ISSUE THREAD

**Issue by wefrenzy** [ValveSoftware/steamvr_unity_plugin#1002]
![1](https://user-images.githubusercontent.com/11494897/147454482-86047cd9-4363-4cb4-a014-29ec3a44e2c9.png)

Please Help Me!!!

My Unity GameView Display A different View with My HTCVive Headset View!
The Center Position is Wrong!

Unity：2020.2.6f1
steamvr_unity_plugin：2.7.3
SteamVR：1.18.7
VivePro2Driver：2.0.18.2

**Comment by zite** [comment]
Seems like you may want to change the Mirror View mode. Since a headset is two eyes that are taller than they are wide what the game view displays can get a little confusing. See the setting here:

![image](https://user-images.githubusercontent.com/198704/149198773-0afc2ff1-e5f5-4520-a4bc-eb095a0ced61.png)
