### ISSUE TITLE
Clarify lack of support for mixed input system usage

### ISSUE THREAD

**Issue by dantman** [ValveSoftware/steamvr_unity_plugin#102]
The releases page has this little note "Fixed some performance issues surrounding using the legacy input system at the same time as the new input system. This is not a supported scenario."

Could it be clarified what usage is not considered supported.

I can think of a few PC games with VR added onto them and a full configuration system built-in that would probably work better with ("Trigger", "Trackpad/Joystick #", "Menu", etc...) buttons than making use of the input system. But which would still make good use of the Skeletal Input API, which indirectly requires configuring the new input system.

**Comment by zite** [comment]
Calls to the old input system (calls based on a button instead of an action) are no longer supported by the new plugin. They are still supported by SteamVR itself (for backwards compatibility) but moving forward the plugin will be focused on the current implementation of SteamVR Input using actions and action sets instead of buttons. The best place for comments on the input system itself is either the OpenVR github: https://github.com/ValveSoftware/openvr/issues or the steam forums: https://steamcommunity.com/app/358720/discussions/
