### ISSUE TITLE
SteamVR codeless initialization

### ISSUE THREAD

**Issue by RoboBatreek** [ValveSoftware/steamvr_unity_plugin#1025]
I'm trying to create a simple input test project to test out a custom made gun that sends input using a Steam VR Tracker 2.0. I started a new project, enabled Unity's XR Plugin Management and imported the newest Steam VR plugin.
I added a bunch of SteamVR_Behaviour_Boolean components to enable and disable Image components that symbolize which button was pressed. Whether in the editor or on build, Steam VR never initializes, and the inputs never get sent.

However I added a SteamVR_Behaviour component whose functionality I am still unsure of, which has a "Initialize Steam VR On Awake" checkbox, and on start, Steam VR initializes.
Moreover, if I add a random SteamVR_Behaviour_Pose component to any object in the scene, Steam VR initializes fine, and the inputs are sent properly, even though it does not explicitly mention that it will call SteamVR.Initialize().
SteamVR_Behaviour_Boolean doesn't seem to call SteamVR.Initialize() at any point.

XR Plugin Management's "Initialize XR on startup" and SteamVR_Settings's "Auto Enable VR" checkboxes are both checked, but Steam VR still does not initialize until manually called from a component.

My main question is; is this by design?
Am I supposed to add SteamVR_Behaviour to initialize Steam VR? Or is it supposed to be initialized on startup based on the checkboxes in Unity and Steam VR's settings?

**Comment by zite** [comment]
Short answer, yes, by design. You'll want to have a SteamVR_Behaviour component on a gameobject. That will do the full initialization on start.

In 99% of use cases people use the SteamVR_Behavior_Pose component, or just the camera rig we provide, so this generally isn't a problem. We do delay full initialization until script runtime so we can properly initialize some of the scriptable gameobject components that need other things to initialize first.
