### ISSUE TITLE
WHY IS THIS VERSION SOOOO CONVOLUTED AND BUGGY???

### ISSUE THREAD

**Issue by superjayman** [ValveSoftware/steamvr_unity_plugin#141]
Show me a simple example in C# to just get the button states? Why do you guys make it so complicated. Do a simple laser pointer example...Simple Button States Example... Keep it Simple Simple Simple..

**Comment by kisak-valve** [comment]
@superjayman, repeatedly opening issues with all caps in the title to repeat what you are posting on #135 is unacceptable. You've earned yourself a 24 hour timeout.

Instead of generic "It's buggy," provide concise information of exactly what is not working for you in your issue report so that the issue report is actionable.
