### ISSUE TITLE
FixedUpdate and unity's tracking pose suck when under high cpu stress

### ISSUE THREAD

**Issue by OriginLive** [ValveSoftware/steamvr_unity_plugin#160]
Hello,
when you induce a high stress cpu environment, the fixed updates get longer and the controller starts jumping and not being smooth. That's shown in the video below, even though i have over 200fps, when my cpu is under stress, the controller will start jumping wildly in unity.
Changing fixed time steps (giving it more time) in the time window helps a little, but not much. Please the controller position fetch function into regular update. Also changed pose/interaction update in settings, doesn't change anything.
Thanks!
https://www.youtube.com/watch?v=jrPkr8cSwWQ

and showing here how i stress it

https://www.youtube.com/watch?v=90OknB7SClc

**Comment by zite** [comment]
I'm not sure what you mean when you say the cpu is under stress. The controllers should not be updating their position in FixedUpdate by default. You can change when the controllers update their position in the SteamVR_Settings asset found in Assets/SteamVR/Resources/SteamVR_Settings.asset. There you'll find "Pose Update Mode" which by default is set to OnPreCull - as close to rendering as we can get.

If you're still seeing the issue can you give a view of the SteamVR frame timing instead of unity's? You can find it here: SteamVR App Menu -> Settings -> Video -> Advanced Frame Timing

**Comment by kisak-valve** [comment]
Closing pending feedback.
