### ISSUE TITLE
Actions from new action set does not bind correctly

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#170]
I cant use the binding UI in the browser because of #154 so I use the UI in the dashboard.

I have created a new action set and binded the actions inside the dashboard UI. Problem is GetActive returns false even when they are binded in the UI and GetStateDown return false when i click the button etc

Bindings in the default action set works

**Comment by AndersMalmgren** [comment]
![image](https://user-images.githubusercontent.com/817577/47465719-5733c900-d7ee-11e8-9268-344c9ecaa791.png)

**Comment by AndersMalmgren** [comment]
Guys please fix docs, its very hard to guess all features. Found the ActivateSecondary browsing the code

**Comment by wywarren** [comment]
I was running into this problem as well. I wanted to use my own action set that's not the default. Thanks for pointing out the ActivateSecondary function. Spent 2-3 days trying to figure out what was wrong with my bindings. I ended up just adding SteamVR_ActionSet reference and calling ActivateSecondary on it in Start(). Turns out you can also pass the argument to the function to disable the default action set as well.
