### ISSUE TITLE
THIS NEW STEAMVR IS A FREAKIN MESS.. WHAT'S GOING ON GUYS??? HELP ME

### ISSUE THREAD

**Issue by superjayman** [ValveSoftware/steamvr_unity_plugin#176]
I'm lost for words , I had so many issues with your release don't know where to begin. You can see the sentiment from the other posts.. Please fix this mess up, or go back to the old version.. For a company of your stature you should not be releasing substandard work.. Too Many Issues For Developers to work around or adapt. eg. If one of the controllers is turned off, the whole thing crashes!!!..

**Comment by ronpetit** [comment]
I'm pretty sure this is not the way to open an issue, if you really have a bad time using the new plugin, just download the old one and keep using it, then, when you are ready to upgrade and learn how to use the new one then change it. I won't deny it have many bugs, but a correct report here is the way to get rid of them

**Comment by superjayman** [comment]
I already did all that.. So what are we suppose to do? Should I be Using the New Plugin?... Yes Or No.. If you don't deny it has many bugs, why release it?

**Comment by kisak-valve** [comment]
@superjayman, your choice to repeatedly open non-actionable issue reports is unacceptable. (#135, #140, #141, and this one)

First, do not use caps in the issue title. Second, provide specific details on what you issues you encounter. Third, have only one issue per issue report so that the issue can be tracked properly.

This issue tracker is not a forum to vent frustration in a non-constructive manner. You have been given a week timeout. The next time I need to step in it will be permanent.
