### ISSUE TITLE
CircularDrive appears to operate in world space

### ISSUE THREAD

**Issue by Problematic** [ValveSoftware/steamvr_unity_plugin#18]
When operating a circular drive, it works fine when I am facing perpendicular (in world space) to the axis of rotation set on the gameObject, rotates backwards when I turn 180 degrees, and more or less twitches without doing anything when I'm facing along the axis of rotation. It appears that the axis of rotation is not being converted properly to the object's local space.

**Comment by aleiby** [comment]
If you want to submit a change to support this, I will integrate it.

**Comment by paulodgn** [comment]
Im sorry to reopen this but im having the exact same problem. Using Unity 2018.1 and the SteamVR plugin for unity. Any way to solve this problem?

**Comment by DeltaMike1010-TM** [comment]
I'm having the same issue. I am  trying to make a vehicle where you have to **drag a lever** to toggle the driving mode between Acceleration and Reverse. The lever **works fine if the vehicle's rotation is similar to the start rotation** of the vehicle. After making a turn or few, **the axis changes from X to Z**. So I have to **grab and drag the lever in Z-axis to rotate it on X-axis** (the lever is supposed to be grabbed and rotated on the X-axis). I'm assuming that this is because of the `worldPlaneNormal` being calculated only in `Start()`. I tried updating the `worldPlaneNormal` every time `ComputeAngle()` is called, but resulted in twitchy rotation. Surprisingly, I also have a steering wheel which uses the CircularDrive component but it works like a charm. Steering wheel uses the Y-axis for rotation.

Is there a work-around for this?
