### ISSUE TITLE
Different snap point for left and right hand

### ISSUE THREAD

**Issue by gizmhail** [ValveSoftware/steamvr_unity_plugin#186]
Maybe I've missed an obvious solution, but it looks like we can only define one unique snap point (through 
Throwable.attachmentOffset or Interactable.handFollowTransform) for a given interactable object.
Thus, it is the same for both hands.

However, I think it is pretty common to have an asymmetrical posture for left and right hands.

Shouldn't we add a second, optional, attribute, such as leftHandFollowTransform, that take the place of handFollowTransfrom when not null ?

**Comment by Danila24ru** [comment]
I join the question. Also I can't understand why attachment offsent (child element) doesn't work.

**Comment by zite** [comment]
In addition to the per item offset there's a per hand offset found on Hand.ObjectAttachmentPoint. This should allow you to do general per hand offsets, then more detailed changes with the attachmentOffset. If neither of those work for you you may need to create a specialized item type that allows configuration per input source.

**Comment by gizmhail** [comment]
Thanks for the answer. I wanted to keep the ObjectAttachmentPoints as close to the default prefab as possible, but they have very different orientations, and in any case, the offset for an object will be asymmetrical.

I'm simply trying to hold a sword currently, and I was looking for an equivalent to the VRTK left/right snap handle.

As you suggest, I'll think about adding a new dedicated component to help in such cases :)

**Comment by gizmhail** [comment]
If someone wants to have 2 different snap points, one for each hand, I've started a script to handle it, available here : https://github.com/gizmhail/SaberTraining/blob/master/Assets/Scripts/SteamVRExtensions/HandSnappable.cs
Still need to be improved, but fell free to use it already if you need :)

**Comment by jschlechte** [comment]
This does seem like a very common use case. @gizmhail might you consider making a PR w/ a recommended solution. @keithbradner would you consider integrating some solution?

The issue is that holding an object (such as a sword/knife/baseball-bat) which needs to be held by the handle and face upward in the hand. What I have found is that by default the object is rotated (not reflected) in the opposite direction in the left hand. So if you hold the sword in the right it is correct, but if you transfer to the left it is now held upside down (as if in a stabbing position). This appears to be due to the `ObjectAttachmentPoint` orientation when `Interactable.useHandObjectAttachmentPoint` is `true`.

However, using raw controller input seems inappropriate, and altering the `ObjectAttachmentPoint` orientation will adversely affect other objects.

This will be increasingly important as more developers are leveraging the skeletal system and Knuckles controllers.

**Comment by jschlechte** [comment]
@keithbradner If it helps highlight the issue here are the left and right offsets required by each hand to properly align the long object within the palm of the hand (note that my object points down the z axis in Unity).

### Right Hand Offset Transform
*Note that the parent transform has a scale of 1.2*
**Position**: [.005,-.0515,0]
**Rotation**: [14.4,66.9,0]
**Scale**: [1,1,1]

### Left Hand Offset Transform
*Note that the parent transform has a scale of 1.2*
**Position**: [.005,**-.0515**,0]
**Rotation**: [**-14.4**,66.9,**180**]
**Scale**: [1,1,1]

#### Right Hand ObjectAttachmentPoint from Player prefab
**Position**: [.052,-.0157,-.1163008]
**Rotation**: [135,-170.9,-90]
**Scale**: [1,1,1]

#### Left Hand ObjectAttachmentPoint from Player prefab
**Position**: [**-.052**,-.0157,-.1163008]
**Rotation**: [135,**170**,**90**]
**Scale**: [1,1,1]
