### ISSUE TITLE
Haptic Rack with LinearMapping not working

### ISSUE THREAD

**Issue by byrontik1** [ValveSoftware/steamvr_unity_plugin#195]
Hi guys

I don't notice the Haptic Rack script producing any haptic feedback on the LinearMapping, neither in the example file. I was wondering if it needs to be triggered On Attached To Hand rather than On Hand Hover.

Thanks 
Byron

**Comment by Thynix** [comment]
If it's helpful, I'm still noticing this in release 2.2.0 with Unity 2018.3.9f1. From my testing, `hand` usually isn't set when `Pulse()` is called, and when it is, `hand.GetBestGrabbingType()` returns `None`, so `TriggerHapticPulse()` is never called.

I was able to get haptics more like what I expected, though without continuation clicks with momentum after release as appear to have been maybe intended, by moving `Update()` to `HandAttachedUpdate()` instead of relying on `OnHandHoverBegin()` and `OnHandHoverEnd()` to set `hand`. I suspect, but did not confirm, that `OnHandHoverEnd()` may be called when attachment begins. I didn't try `OnAttachedToHand()` as @byrontik1 suggested because it took me this long to understand what that meant.

**Comment by zite** [comment]
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!
