### ISSUE TITLE
Render Models don’t show up in LWRP

### ISSUE THREAD

**Issue by zite** [ValveSoftware/steamvr_unity_plugin#210]
Unity’s light weight render pipeline does not include the standard shader so render models don’t show up properly. See: https://www.reddit.com/r/SteamVR/comments/a0o5jp/vive_controllers_material_not_showing_in_unity/?st=JOZD7XK2&sh=cf9c5d12

**Comment by baratgabor** [comment]
What's particularly problematic is that the plugin contains custom shaders, e.g. for teleport highlight. And I have no idea how to update custom shaders for LWRP. :P

**Comment by jgwinner** [comment]
This is a killer; using the LWRP would seem to be a no brainer, as is using SteamVR.

**Comment by jonathan-bryant** [comment]
> This is a killer; using the LWRP would seem to be a no brainer, as is using SteamVR.

I completely agree, would be great to be able to use shadergraph to adjust shaders too.

**Comment by jgwinner** [comment]
Old issue, but is this now fixed with URP?

**Comment by jgwinner** [comment]
If URP has not fixed this, this issue is still open. It's absurd that it was never closed. LWRP is important for VR, as is Steam VR. This should have been a critically high issue. 

Ah, maybe it's a duplicate of https://github.com/ValveSoftware/steamvr_unity_plugin/issues/422 but a comment on the closure would have been nice.
