### ISSUE TITLE
Is There any Documentation of your latest SteamVr, I want it to Use For Multiplayer..

### ISSUE THREAD

**Issue by AliMumtazCH** [ValveSoftware/steamvr_unity_plugin#225]
Hello ,
It is to ask from you guys that is there any documentation Of your latest SteamVR Unity Plugin v2.1.5b2  
I want to use it for making multiplayer game .
I also Want to ask 
 //private SteamVR_Controller.Device steamDevice;
below line is used in public override void OnStartAuthority()
{//steamDevice =SteamVR_Controller.Input((int)trackedController.GetComponent<SteamVR_TrackedObject>().index);
}
 //currentVelocity = steamDevice.velocity;
from which these things are Exchanged with 
Thanks 
I hope you People can Help Me ASAP.

**Comment by zite** [comment]
Sorry there is no specific documentation relating to multiplayer. You may have better luck asking in a unity forum as this seems like more of a unity specific question rather than a steamvr question. https://answers.unity.com/index.html

Specifically the SteamVR_Controller class is deprecated. You'll want to use the SteamVR_Behaviour_Pose component and then you can call GetVelocity() on that component.

I might also recommend going through the tutorial here: https://steamcommunity.com/sharedfiles/filedetails/?id=1416820276
