### ISSUE TITLE
I want To Ask Regarding SteamVr_controller Alternate

### ISSUE THREAD

**Issue by AliMumtazCH** [ValveSoftware/steamvr_unity_plugin#238]
private SteamVR_Controller.Device steamDevice;
steamDevice = SteamVR_Controller.Input((int)trackedController.GetComponent<SteamVR_TrackedObject>().index);
steamDevice.GetTouchDown (SteamVR_Controller.ButtonMask.Trigger)
what will be the alternate to get i want it to know to set it up for my Multiplayer Controll Syncing I want these Lines to be Done In different Functions but I want to Have Its Alternate with new steamvr plugin.
I am anxiously waiting for reply, i hope you guys will help me out!

**Comment by zite** [comment]
Unfortunately there's not a clean transition between the two systems. The new SteamVR Input System uses actions instead of button ids. 

You can read the pdf documentation included with the plugin here:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/master/Assets/SteamVR/SteamVR%20Unity%20Plugin%20-%20Input%20System.pdf

Here's a tutorial I wrote:
https://steamcommunity.com/sharedfiles/filedetails/?id=1416820276

Here's a list of some youtube video's I've found by other people:
https://www.youtube.com/watch?v=bn8eMxBcI70 (basic)
https://www.youtube.com/watch?v=lOaR-cUGzkc (haptics)
https://www.youtube.com/watch?v=zs6uNttLh-k (vive tracker)
https://www.youtube.com/watch?v=HnzmnSqE-Bc (simple interaction)
