### ISSUE TITLE
SteamVR v2.2b4 NullReferenceException in SteamVR_Action_Boolean.GetStateDown

### ISSUE THREAD

**Issue by gkapellmann** [ValveSoftware/steamvr_unity_plugin#263]
Hello, 

The issue appeared after I started trying to implement a "Linear Drive". Before I was using only "Throwable" and it was working well. Then after trying to add the Linear Drive and configuring it, it started to show the error. Now I have deactivated all prefabs to try and spot what broke it, but the error now is always appearing. It sends me to Player and to the script SteamVR_Action_Boolean. 

I have tried to delete Player and re-introduce it and to re-save and generate the bindings and nothing has changed. 

If clicked, the error sends me to "SteamVR_Action_Boolean.cs" and is pointing to a specific line:

Line 80: Return sourceMap[inputSource].stateDown;

**Comment by gkapellmann** [comment]
I get that idea, but the problem is appearing even when I just put the "Player" prefab only in the scene and nothing else, all the rest of the prefabs (including the floor) have been disabled or eliminated.

**Comment by zite** [comment]
Have you deleted or renamed the default actionset? Or any of the default actions? (gripgrab, pinchgrab, etc).

**Comment by gkapellmann** [comment]
Hello again @keithbradner, yeah i have. I've done that twice already.

So how can i trace the error? If i do double click on it as I have explained before it sends me to the script SteamVR_Action_Boolean from player. I have noticed that if i deactivate the two hand prefabs the error stops, but of course there are no controllers then. So how can i trace that error?

**Comment by zite** [comment]
It should be in the trace of the error itself. If you post the full error I can point you at where to look. I'll consider how this can be better though as I understand this is frustrating.

**Comment by gkapellmann** [comment]
Ok, so the trace of the error says this:

NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Action_Boolean.GetStateDown (Valve.VR.SteamVR_Input_Sources inputSource) (at Assets/SteamVR/Input/SteamVR_Action_Boolean.cs:79)
Valve.VR.InteractionSystem.Player.Update () (at Assets/SteamVR/InteractionSystem/Core/Scripts/Player.cs:289)

Thank you for your help!

**Comment by zite** [comment]
So the last line of that error is where you want to look. Assets/SteamVR/InteractionSystem/Core/Scripts/Player.cs:289

That refers to the headsetOnHead action on the Player component (which is a proximity sensor thing). You can set that to another action doing the same thing, remove that code, or I believe just explicitly setting the action to None should work too. I'll try and get this fixed in the next beta so it fails cleanly.

**Comment by gkapellmann** [comment]
I just did the update to the new release, and yes, now the error has disappeared. I know that then this will be closed, can you just explain very briefly what was it? I'm a bit confused after checking those lines of code.

Thank you for your help!

**Comment by zite** [comment]
SteamVR_Action is kind of a weird object, we do custom serialization and deserialization on it and override the ==, !=, and .Equals operators on it to smooth dev user experience. Specifically because a SteamVR_Action can be created for an action that has not been set, so when you compare it to null it should return true as it isn't a real action. Somewhat similar is how Unity will return true for gameobject == null when it hasn't actually been deleted yet, but has effectively been removed from a scene.

So previously you had deleted the headsetOnHead action, or renamed the action set it was in, or something to that effect so in the Player component that headsetOnHead variable was no longer set. But it still had a serialized value under the hood, just not in reference to any actual action. So `if (headsetOnHead != null)` was returning true even though there wasn't a real action associated.
