### ISSUE TITLE
How to send a haptic pulse to the Vive Tracker?

### ISSUE THREAD

**Issue by Admiral-Wol** [ValveSoftware/steamvr_unity_plugin#289]
Hi,

I'm trying to receive haptic feedback from my Vive Trackers. I'm using SteamVR 2.0 Plugin for Unity. I already did it on earlier versions of the SteamVR Plugin, but since a major update, I've lost the commands for relaying the haptic feedback to and from the tracker. "TriggerHapticPulse();" particularly was used for earlier versions of SteamVR. But now I can't seem to be able to use it. Please help.

**Comment by zite** [comment]
It looks like HTC manages this feature of the firmware. I believe you'll have to talk to them to get this fixed.

**Comment by Cresset50c1** [comment]
> It looks like HTC manages this feature of the firmware. I believe you'll have to talk to them to get this fixed.

Hello @keithbradner 

Its been a month and we are still facing this issue, no reply from htc vive, i believe if you guys are managing this git, please tell what function i can call to trigger haptic pulse from general purpose output pin?

**Comment by CarlosMeloStuff** [comment]
I have had the same problem for months, I have 4 trackers and I have tested the haptic feedback on Arizona sunshine and other games that support the hyperblaster and used to have haptic feedback for the trackers and also in Unity an I can't get it to work. I have open the hyperblaster and confirm that the vibrator motor works correctly by connecting it to an external power source so the problem seems to be the steamvr software.

I have tried contacting Vive and Steam developers but they haven't responded.
