### ISSUE TITLE
"Open Binding UI" button throws error and does not open anything

### ISSUE THREAD

**Issue by blackpandastudios** [ValveSoftware/steamvr_unity_plugin#311]
Hey,

So I am on the latest version of SteamVR and on unity 2018.3.0f2, but for some reason I am unable to open the binding UI.

![notopeninggif](https://user-images.githubusercontent.com/40645358/52376424-39952180-2ab6-11e9-87df-ba797781c7f9.gif)

Attached is a Gif of me attempting to open it.
I'll also attach the error messages.

**The First error thrown:**
`SteamVR]</b> Error during OpenVR Init: Init_HmdNotFoundPresenceFailed
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR:InitializeTemporarySession(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:306)
Valve.VR.SteamVR:ShowBindingsForEditor() (at Assets/SteamVR/Scripts/SteamVR.cs:340)
Valve.VR.SteamVR_Input_EditorWindow:OpenControllerBindings() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:522)
Valve.VR.SteamVR_Input_EditorWindow:DrawSave() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:507)
Valve.VR.SteamVR_Input_EditorWindow:OnGUI() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:454)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

**The Second Error Thrown:**
`ullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR.ShowBindingsForEditor () (at Assets/SteamVR/Scripts/SteamVR.cs:343)
Valve.VR.SteamVR_Input_EditorWindow.OpenControllerBindings () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:522)
Valve.VR.SteamVR_Input_EditorWindow.DrawSave () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:507)
Valve.VR.SteamVR_Input_EditorWindow.OnGUI () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:454)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:342)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:336)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:310)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean customBorder, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:363)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:322)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:266)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:438)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:421)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleEvent (UnityEngine.Experimental.UIElements.EventBase evt) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:401)
UnityEngine.Experimental.UIElements.EventDispatcher.ProcessEvent (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:511)
UnityEngine.Experimental.UIElements.EventDispatcher.Dispatch (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel, UnityEngine.Experimental.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:307)
UnityEngine.Experimental.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.Experimental.UIElements.EventBase e, UnityEngine.Experimental.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:176)
UnityEngine.Experimental.UIElements.UIElementsUtility.DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:245)
UnityEngine.Experimental.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:68)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)`

**Comment by zite** [comment]
Do you have steamvr installed on this computer, steamvr running, and a headset connected? You'll need these things to use the binding ui.

**Comment by blackpandastudios** [comment]
Wait so I can't access the binding UI when a headset is not connected?

Just curious why this is a requirement?

I am updating my Unity Asset to fully support SteamVR 2.0, and just wanted to generate and bind a new actionset to contain a vector2 for thumb position on the train, obviously can't really have a headset connected while I do this.

Can I fake a headset being connected just so I can develop on the go without that requirement?

**Comment by blackpandastudios** [comment]
Sorry, I may just be misinterpreting the new input system? From a video I watched, it seems like I have to open this interface to set-up stuff for my development environment to use? for example, thumb position, as it is not in the default set?

Also, another question, what advice would you give to VR Asset Store publishers trying to sell an asset without being able to package the actionset with the package? 

Thanks for the support so far :)

**Comment by zite** [comment]
Unfortunately, as it is, the binding ui shows information specific to the
headset you currently have connected. If you don’t have one connected it
can’t display anything. It loads this information from the SteamVR driver
specific to that headset.

I understand this isn’t necessarily intuitive, especially to devs that have
been working with SteamVR previously.

From your message I’m not clear on why you can’t have a headset connected
to do this.

Alternatively, you can manually edit the default JSON files (actions.json
and bindings) in the root of your project directory, open the binding ui,
and “save and generate”. It’s easier if you edit the jsons while the
project is closed but if you do it while it’s open be sure to go to
advanced and hit Refresh to load the new actions file.

**Comment by blackpandastudios** [comment]
Ohh that is interesting.

I couldn't have a headset connected because I was on the train into work that's all.

I'll look into manually editing the .json files as an alternative. I was just misinterpreting the binding UI I think, but I do now get the reasoning behind it all.

Thanks for the support and helping me understand that clearer :)

**Comment by ruanrothmann** [comment]
Hi, so my understanding is that we use the binding UI to set the defaults for the various headsets, correct? So, how do I then set default controls for eg WMR or a headset that we do not possess?

**Comment by limaoscar1** [comment]
@keithbradner  
Im currently using unity 2019.2.6. the new version of steamVr unity plugin 2.4, SteamVr is installed on my pc. The device I'm  using the the valve index with controllers.

i have followed the getting started  guide, and i cant open the UI binding menu at all.
I assumed it was because i was trying to use the HDRP, but did it with out the SRP and i still get the same error.


 this is the first error i get. 
<b>[SteamVR]</b> Error during OpenVR Init: Init_InterfaceNotFound
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR:InitializeTemporarySession(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:320)
Valve.VR.SteamVR:ShowBindingsForEditor() (at Assets/SteamVR/Scripts/SteamVR.cs:354)
Valve.VR.SteamVR_Input_EditorWindow:OpenControllerBindings() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:522)
Valve.VR.SteamVR_Input_EditorWindow:DrawSave() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:507)
Valve.VR.SteamVR_Input_EditorWindow:OnGUI() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:454)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

This is second error.
NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR.ShowBindingsForEditor () (at Assets/SteamVR/Scripts/SteamVR.cs:357)
Valve.VR.SteamVR_Input_EditorWindow.OpenControllerBindings () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:522)
Valve.VR.SteamVR_Input_EditorWindow.DrawSave () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:507)
Valve.VR.SteamVR_Input_EditorWindow.OnGUI () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:454)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:359)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:353)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:329)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:374)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:341)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:298)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:483)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:466)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:447)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/Events/MouseCaptureDispatchingStrategy.cs:93)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:280)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:156)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:190)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:255)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:78)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by joostbos** [comment]
I get the same error on Unity 2019.2.6f1 with the SteamVR 2.4.3 plugin with my HTC Vive connected and switched on. Also the controllers are on. Everything is green/blue gradient in SteamVR 1.7.15. I made sure the Vive and controllers were on and tracking before starting Unity.

I got the following errors twice when opening Unity:
`[SteamVR] Error during OpenVR Init: Init_InterfaceNotFound
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR:InitializeTemporarySession(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:320)
Valve.VR.RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
Valve.VR.SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:303)
Valve.VR.SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:721)
`
and 
`[SteamVR] Failed to load IVRRenderModels interface version IVRRenderModels_006
UnityEngine.Debug:LogError(Object)
Valve.VR.RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:95)
Valve.VR.SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:303)
Valve.VR.SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:721)`

And then when I click Open Binding UI I get:
`[SteamVR] Error during OpenVR Init: Init_InterfaceNotFound
UnityEngine.Debug:LogError(Object)
Valve.VR.SteamVR:InitializeTemporarySession(Boolean) (at Assets/SteamVR/Scripts/SteamVR.cs:320)
Valve.VR.SteamVR:ShowBindingsForEditor() (at Assets/SteamVR/Scripts/SteamVR.cs:354)
Valve.VR.SteamVR_Input_EditorWindow:OpenControllerBindings() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:522)
Valve.VR.SteamVR_Input_EditorWindow:DrawSave() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:507)
Valve.VR.SteamVR_Input_EditorWindow:OnGUI() (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:454)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

and

`NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR.ShowBindingsForEditor () (at Assets/SteamVR/Scripts/SteamVR.cs:357)
Valve.VR.SteamVR_Input_EditorWindow.OpenControllerBindings () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:522)
Valve.VR.SteamVR_Input_EditorWindow.DrawSave () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:507)
Valve.VR.SteamVR_Input_EditorWindow.OnGUI () (at Assets/SteamVR/Input/Editor/SteamVR_Input_EditorWindow.cs:454)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:359)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:353)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:329)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:374)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:341)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:298)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:483)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:466)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:447)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/Events/MouseCaptureDispatchingStrategy.cs:93)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:280)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:156)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:190)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:255)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:78)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
`
I hope someone can help me, because apparently just switching on the Vive is not the solution.

Thanks!

**Comment by dariol** [comment]
You don't need the hmd if you're not creating new actions and simply want the updated defaults included in the plugin copied over to your project.  Use the option to copy over the example files instead of opening the binding UI then hit generate save.

**Comment by joostbos** [comment]
Can you point me to an overview of those default actions for the Vive? What action is called when I press the trigger, is that GrabGrip? And what if I press the grip?

I am trying to understand the new mechanism by following tutorials, but they all at some point rely on pressing the Open Binding UI button, so there it stops for me.

Anyway, I think I will need to add new actions. In some scenes the trigger button needs to launch a ball, in other scenes it needs to start a trail, like in tilt brush.

**Comment by limaoscar1** [comment]
@joostbos 
to try and solve it i used a legacy version in unity 2019.1 ,  i can get the controllers to work  but i need to moves the json files into the root. Im  kinda struggling to get this to work at the moment.

**Comment by joostbos** [comment]
@limaoscar1 
Thanks for the suggestion, but I already have 5 Unity versions clogging up my system, so I'd rather not add another one. I hope @keithbradner can shine some light on this.

**Comment by chengnay** [comment]
@joostbos Did you try updating your SteamVR Plugin to v2.4.5, I overcome some of your errors too, but in v2.4.5, it should be fixed.

**Comment by slampants** [comment]
I'm experiencing the same problem, running Unity 2019.2.0f1 with SteamVR v2.5 (sdk 1.8.19).

**Comment by slampants** [comment]
I noticed when I tried switching to VRTK and that my controllers weren't syncing at all to the default game objects, even in a VRTK demo scene, and it was showing a bunch of missing prefabs. Giving me different errors and warnings. Even starting a brand new Unity project would do the same, problems with both VRTK and SteamVR. So I figured it was something at a more system level and decided to firebomb the whole VR base and start over:

- Uninstalled all of my Vive and SteamVR software (everything windows uninstaller could find with vive in the title, or VR that wasn't a steam game, basically)
- Physically disconnected my Vive from ViveWireless
- Downloaded the setup .exe from HTC for setting up Vive, and ran through installation as if I was a brand new customer, setting up the Vive in wired mode instead of re-installing wireless
- Started a brand new project in Unity 
- Brought in SteamVR before anything else, tested a demo scene to confirm everything was fine. It was
- Gradually started loading in all the scripts and prefabs from my previous project. Everything still works, and have started building from there

The two things I still haven't done:
- Import scenes from previous project (Guessing it'll be fine since before even the demo scenes from VRTK and SteamVR were broken)
- Set up ViveWireless

Will update if and when I do those.
