### ISSUE TITLE
Clarification on process for using custom hand models

### ISSUE THREAD

**Issue by Wyattari** [ValveSoftware/steamvr_unity_plugin#332]
Hey everyone,

I cannot figure out how to connect a custom mesh (or even the default vr glove mesh) to the provided skeleton. [Here is what it looks like when I import the default vr glove to Maya.](https://imgur.com/hQs80x0) Even if I freeze the transforms on everything to make the rig look like a skeleton & bind it to the model, upon importing back to Unity there are a host of transformation issues -- gloves pointing the wrong way, the root rotating Y at 180 on play, odd skeleton scaling, skeleton & mesh not lining up on play, etc.. The closest I've gotten is the proper skeleton position, but my mesh looking inside out. 

The closest documentation I can find is the [hand-skeleton page](https://github.com/ValveSoftware/openvr/wiki/Hand-Skeleton), but it's pretty high level and doesn't deal with how the skeleton is specifically implemented in the plugin.

Any clarification that can be provided on how to properly prep your hand model, bind it with the existing skeleton, and implement back into the plugin would be greatly appreciated.

All the best,
Wyatt

**Comment by joevdh** [comment]
OpenVR's units are in meters, but Maya defaults to cm.  With default FBX settings (automatic unit conversion) the way Maya handles this conversion change is to apply a scale of 100 to the root bone when it import the FBX.  If you import the skeleton and glove from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\vr_glove\vr_glove_right_model.fbx you'll see the scale of 100 on both the Root bone and the glove mesh.  When you export the same file from Maya back to FBX the automatic export settings have done the right thing for me, and I've been able to drop the model in Unity and it imports ok.  

I'd suggest trying to apply a scale of 100 to your new hand model when binding it to the skeleton so that it behaves like the vr_glove model when you export it.  

Also, the Maya rendering of the joints can look really screwy when dealing with things in other units (like in your picture).  You can adjust the size of the joints by going to Display ->Animation -> Joint Size...   I use a size of 0.01 by default.

**Comment by Wyattari** [comment]
Hey Joe,
Thanks for the input. I've got the right scale for the models & skeleton now, but there still is something going on with the orientation. [Here's what happens](https://giant.gfycat.com/BoldFrightenedAquaticleech.webm) when I try to use the default vr_glove imported directly from the Steam\steamapps\common\SteamVR\resources\rendermodels\vr_glove folder into Unity. As you can see it looks like there are issues with the skeleton orientation. 
![image](https://user-images.githubusercontent.com/9206357/53479645-53c77d00-3a2e-11e9-942f-fc3b3d09e542.png) To reproduce this just replace the plugin model & skeleton with the Steam resources folder model & skeleton in the "vr_glove_right" prefab.

**Comment by joevdh** [comment]
Ah, I think I know what's going on.  The plugin is expecting the bones to be in the order defined by the Skeletal Input standard skeleton.  But for some reason Unity insists on sorting the bones alphabetically when it imports an FBX.  So you just have to re-order the finger bones in the hierarchy to go thumb, index, middle, ring, pinky, then the same with the aux bones, like this:

![boneorder](https://user-images.githubusercontent.com/17608394/53507842-7dec5f80-3a6d-11e9-80c7-cc62bc5fcce1.PNG)

**Comment by Wyattari** [comment]
Success! That solves it. It also might be good to note that by default there is no mirroring on the right hand, but there **is** mirroring "Right To Left" for the left hand in the Steam VR_Behaviour_Skeleton component. Thanks for the clarification!
