### ISSUE TITLE
SteamVR 2.2 + nvidia Flex errors

### ISSUE THREAD

**Issue by doukasd** [ValveSoftware/steamvr_unity_plugin#337]
I am trying to use the SteamVR Plugin with the nvidia Flex fluid renderer. On their own, they all work fine. But when combined, there are runtime errors.

Setup:
- Unity 2018.3.6f1 (latest at this time)
- SteamVR Plugin 2.2 (latest from asset store)
- nvidia Flex for Unity 1.0.5 (latest from asset store)

Steps to reproduce:
- Create a new Unity project
- Import the SteamVR Plugin from the store
- Import nvidia Flex for Unity from the store
- Turn on your VR system (HTC Vive in my case)
- Open the flex no.9 Fluid Renderer sample scene, press Play and observe the fluid flow fine in VR
- Now disable the `Camera` in that scene and drop in the `[CameraRig]` from the SteamVR prefabs
- Press Play now and observe that the fluid stops flowing after a few seconds and the following errors appear:

```
ArgumentException: ComputeBuffer.SetData() : Accessing 35100 bytes at offset 0 for Compute Buffer of size 35000 bytes is not possible.
UnityEngine.ComputeBuffer.SetData (System.Array data) (at C:/buildslave/unity/build/Runtime/Export/ComputeShader.bindings.cs:124)
NVIDIA.Flex._auxFlexDrawFluid.UpdateMesh (NVIDIA.Flex.FlexContainer+ParticleData _particleData) (at Assets/NVIDIA/Flex/Auxiliary/_auxFlexDrawFluid.cs:247)
NVIDIA.Flex.FlexContainer.UpdateDrawFluid (NVIDIA.Flex.FlexContainer+ParticleData _particleData) (at Assets/NVIDIA/Flex/Assets/FlexContainer.cs:788)
NVIDIA.Flex.FlexContainer.UpdateSolver () (at Assets/NVIDIA/Flex/Assets/FlexContainer.cs:696)
NVIDIA.Flex.FlexContainer.FixedUpdate () (at Assets/NVIDIA/Flex/Assets/FlexContainer.cs:605)
NVIDIA.Flex.FlexScene.FixedUpdate () (at Assets/NVIDIA/Flex/Helpers/FlexScene.cs:68)
```

```
LogWarning - Mapping a buffer that was already mapped
File - ..\..\dx\utils.cpp (62)
UnityEngine.Debug:LogError(Object)
NVIDIA.Flex.FlexContainer:ErrorCallback(ErrorSeverity, IntPtr, IntPtr, Int32) (at Assets/NVIDIA/Flex/Assets/FlexContainer.cs:491)
NVIDIA.Flex.FlexExt:MapParticleData()
NVIDIA.Flex.FlexContainer:UpdateSolver() (at Assets/NVIDIA/Flex/Assets/FlexContainer.cs:688)
NVIDIA.Flex.FlexContainer:FixedUpdate() (at Assets/NVIDIA/Flex/Assets/FlexContainer.cs:605)
NVIDIA.Flex.FlexScene:FixedUpdate() (at Assets/NVIDIA/Flex/Helpers/FlexScene.cs:68)
```

I understand that it seems to be Flex "crashing" here and not SteamVR, which is why I first posted this issue on the [nvidia forums](https://devtalk.nvidia.com/default/topic/1047717/general/flex-unity-v1-0-5-steamvr-fluid-error/#), however as SteamVR is implicated (Flex works fine without it) I am here to see if SteamVR Plugin could be improved in some way to not affect other such systems.

**Comment by rt974** [comment]
Hi, i am a bit familiar with compute shaders, this is due to the computebuffer size that was containing xxx amount of particles when initilialzed earlier, and then the flex source actor added more particles, but the buffer size wasnt updated. im having the same issue in unity and the flex plugin. i think i can debug this, did some compute shader coding last month. if i manage to fix that ill post the solution there.

For example, if you set the fluid source actor particle life to a high number like : 999, when the source actor spawns its particles, it has to wait 999 seconds before adding anymore particles to the simulation, and having to update the compute buffer size, so it runs fine as long as no new particles are added.

But i need this to be fixed so ill take a look and see if i can resize the compute buffer according to the new particles count. This shouldnt require any PHD in Astrophysics, because i got none.

:-)

**Comment by rt974** [comment]
here for example in _auxFlexDrawFluid.cs at the line 247 :

if you replace m_indexBuffer.SetData(indices);

by 

`if(indices.Length != m_indexBuffer.count)
{
	m_indexBuffer = new ComputeBuffer(indices.Length, sizeof(int));

}
else
{
	m_indexBuffer.SetData(indices);
}`

The error is gone, but because we recreate the buffer every single time we add a particle, this creates a flickering. Ill see if i can fix that, with my poor understanding of computer graphics.

**Comment by rt974** [comment]
Wow i managed to fix this :

`csharp
//ORIGINAL
//m_indexBuffer.SetData(indices);
//ORIGINAL
//NEW
if(indices.Length != m_indexBuffer.count)
{
	m_indexBuffer = new ComputeBuffer(indices.Length, sizeof(int));
	m_indexBuffer.SetData(indices);
}
else
{
	m_indexBuffer.SetData(indices);
}
//NEW
`

**Comment by reforia** [comment]
> Wow i managed to fix this :
> 
> ```cs
> //ORIGINAL
> //m_indexBuffer.SetData(indices);
> //ORIGINAL
> //NEW
> if(indices.Length != m_indexBuffer.count)
> {
> 	m_indexBuffer = new ComputeBuffer(indices.Length, sizeof(int));
> 	m_indexBuffer.SetData(indices);
> }
> else
> {
> 	m_indexBuffer.SetData(indices);
> }
> //NEW
> ```
> 
> The flicker happened because the SetData needs to be called in all cases, the code can be simplified by removing the else, and writing only one SetData at the end.
> 
> Now for me this works, i dont really know if this doesnt create side effects, i've read somewhere on unity forums that recreating ComputeBuffer every frame is not a good idea. Thats as far as my knowledge goes on this topic.
> 
> I hope this helps.

**Comment by reforia** [comment]
@rt974 Thanks for the solution! that helps me solve the problem!

After a lil' bit investigation I think your solution can be better by adding another line
`        m_indexBuffer.Release();`
before:
`	m_indexBuffer = new ComputeBuffer(indices.Length, sizeof(int));`

Which releases the buffer created at line 242 before recreating it, otherwise it will throw back some warnings by Unity Garbage Collection

The code will then be:
```
                    if (indices.Length != m_indexBuffer.count)
                    {
                        m_indexBuffer.Release();
                        m_indexBuffer = new ComputeBuffer(indices.Length, sizeof(int));
                    }
                    m_indexBuffer.SetData(indices);
```

**Comment by zite** [comment]
Thanks for the help!

**Comment by oli414** [comment]
The solution by @reforia keeps the number of drawn particles at the maximum. This becomes a problem when deactivating the fluid source, as the fluids will not despawn until every single one of them has reached the end of its lifetime.
Instead I propose this workaround.

Replace:
`m_indexBuffer.SetData(indices);`
in _auxFlexDrawFluid.cs
with:
`m_indexBuffer.SetData(indices, 0, 0, m_indexBuffer.count);`

**Comment by lokeshkumar16061993** [comment]
> Hi, i am a bit familiar with compute shaders, this is due to the computebuffer size that was containing xxx amount of particles when initilialzed earlier, and then the flex source actor added more particles, but the buffer size wasnt updated. im having the same issue in unity and the flex plugin. i think i can debug this, did some compute shader coding last month. if i manage to fix that ill post the solution there.
> 
> For example, if you set the fluid source actor particle life to a high number like : 999, when the source actor spawns its particles, it has to wait 999 seconds before adding anymore particles to the simulation, and having to update the compute buffer size, so it runs fine as long as no new particles are added.
> 
> But i need this to be fixed so ill take a look and see if i can resize the compute buffer according to the new particles count. This shouldnt require any PHD in Astrophysics, because i got none.
> 
> :-)

its perfectly worked for me thank you
