### ISSUE TITLE
Binding UI window pop up every time.

### ISSUE THREAD

**Issue by liziteng** [ValveSoftware/steamvr_unity_plugin#344]
Hi there, I am recently encounter with an issue, where I am running my game test, a “binding is not set” window will pop-up automatically. I am using steamVR 2.2, Unity 2018.3.1f1. This issue happens after I copy my project folder to a new computer, I don’t know if this is the case, but right now even if I started a new project this window will pop up.

**Comment by liziteng** [comment]
This issue could be solved after reinstal SteamVR from Steam. This maybe a bug from Steam.

**Comment by liziteng** [comment]
Today I used an another computer to test out, same project nothing had changed, and this pop-up whindow didn’t show up. It seems that only happen to my home computer. I think there maybe some setting goes wrong.

**Comment by liziteng** [comment]
Answer is here: https://stackoverflow.com/questions/41418481/in-unity-how-to-stop-popup-for-show-unity-splashscreen

**Comment by spayne** [comment]
What you have said yesterday a splashscreen doesn't match what you were talking about earlier (a bindings window).

If the problems is a bindings window, and is saying something like "Binding for [GameName] was not set. Please select a binding option. [Close]

Then you need to use the Controller Bindings GUI and go through each of your controllers and make sure that a default binding is setup for each controller.  E.g. If at home you have an xbox controller and steam has detected it, you need to make sure there is a binding (can be empty) is set for the xbox controller.  Otherwise you will get that dialog box.

**Comment by liziteng** [comment]
> What you have said yesterday a splashscreen doesn't match what you were talking about earlier (a bindings window).
> 
> If the problems is a bindings window, and is saying something like "Binding for [GameName] was not set. Please select a binding option. [Close]
> 
> Then you need to use the Controller Bindings GUI and go through each of your controllers and make sure that a default binding is setup for each controller. E.g. If at home you have an xbox controller and steam has detected it, you need to make sure there is a binding (can be empty) is set for the xbox controller. Otherwise you will get that dialog box.

Oh, Thank you Spayne, the Xbox controller is the problem. Saved my day.
