### ISSUE TITLE
Interectable object inside another interectable object

### ISSUE THREAD

**Issue by JesusNexus** [ValveSoftware/steamvr_unity_plugin#399]
Hi, 

I would like to know how to prioritize an interectable object  inside another interectable object.

For example, I attach a photo where I have an object that when I put it inside a drawer, I can not pick it up again because the drawer (also interectable) activate when i try it.
 
Thank you.

![DrawerSteamVR](https://user-images.githubusercontent.com/43813802/55941098-cfc5ff00-5c41-11e9-9225-e2e8e503206e.png)

**Comment by Servonius** [comment]
You are using the "desktop" mode of SteamVR which uses a Raycast (from the camera to the sphere) for interacting with objects. This shouldn't be a problem when you use the controllers.

But you could use a (convex) mesh collider for your drawer instead of a Boxcollider, with that the Raycast hits the box inside the drawer.

**Comment by zite** [comment]
@Servonius answer seems pretty good! Thanks.
