### ISSUE TITLE
Can't set default binding for controllers.

### ISSUE THREAD

**Issue by finnusmagic** [ValveSoftware/steamvr_unity_plugin#451]
Hey,
When I try to set a default binding for my Unity project, it wont safe the changes. What I try to do is to open the binding UI, create a binding and then I use the "replace default binding" button. But when I save and generate it in Unity, there still is no default binding set. In the editor that is no issue, because the input works as it should. But when I make a unity build, the binding is missing. I even tried to set the default binding manually in the "actions.json" file by changing the following lines from:

"default_bindings": [],

to this:

"default_bindings" : [
      {
         "binding_url" : "system_generated_myproject_exe_binding_oculus_touch.json",
         "controller_type" : "oculus_touch"
      }
   ],

But as soon as I generate it, the default binding is empty again. I feel like it's either a bug or I'm missing something. My goal is to create a working binding for Oculus, Vive and Index. 

Hope someone can help!
Thanks and best regards,
Finn

**Comment by zite** [comment]
When you say the default binding is empty, do you mean in the binding ui? that file? or both?

Are there any errors when you save and generate?

**Comment by chakravarthye** [comment]
Hi @keithbradner,

I am using the Oculus Rift S, steamVR 2.3.2 in unity. Somehow the head tracks properly but the hand controls don't seem to do anything. I am mostly doing all the steps in the youtube tutorials.
1. create some objects
2. drag in the [Camera rig] prefab
3. in the steamvr Input window I click the generate and save.

When I hit play, only the head is tracking and the hand controllers dont seem to be there. Can you please suggest me where I could be going wrong.

**Comment by dopegames** [comment]
I've been experiencing this problem for awhile now and wasn't sure if it was a bug or if I was doing something incorrectly. To elaborate on the issue, let me provide some context. 

I'm currently developing a VR game using Unity 2018.3.5f1 with the latest SteamVR Unity plugin 2.5.0 (sdk 1.8.19)  and SteamVR App 1.10.28. I have only 3 action sets default, vive, & index, all of which work perfectly fine when developing and running the game within the editor. Once I have implemented a new feature and want to test, I create a build and then run the application. On the very first build, I was prompted with a message stating that the Index Controller binding was not set. Please select a binding option from the list or create a new one. When this happened the first time, I did what it said and assigned all the actions, per set, to the corresponding controller. Which is a pain, when dealing with multiple controllers, or action sets. Once all actions have been assigned, the SteamVR hands show up and I can run the application. But lets say I make a change and create a brand new build, I'm prompted with the same error message with no ability to access the Bindings and had just set previously. Because of this hiccup it has caused me to do most development directly in the editor, without ever testing in an actual build because I know how long it will take to reassign all the actions. Especially if I create new ones and have to rebuild.

**Comment by zite** [comment]
There's too many issues here, if any of these are still problems please search for a relevant issue or create a new one. Thanks.
