### ISSUE TITLE
SteamVR_UpdatePoses deprecation removes the controllers

### ISSUE THREAD

**Issue by danksky** [ValveSoftware/steamvr_unity_plugin#49]
There is no way to see the controllers with the current version of the SteamVR plugin. Even adding the Update Poses script to the Camera component in the `[CameraRig]` doesn't do anything because the script is automatically removed now with this message:

> SteamVR_UpdatePoses has been deprecated - REMOVING
> UnityEngine.Debug:Log(Object)
> SteamVR_UpdatePoses:Awake() (at Assets/SteamVR/Scripts/SteamVR_UpdatePoses.cs:14)
> UnityEditor.HostView:OnGUI()

**Comment by bddckr** [comment]
That's because the poses are updated in a way that means no additional component is necessary anymore. Working fine for me on Win10, SteamVR release branch, SteamVR plugin 1.2.2, Unity 5.6.0f3, 5.6.2p3, 2017.1.

**Comment by peterept** [comment]
I'm using 2017.2.0b4 and I only see the Vive wands in the editor scene window and not in game window.

Repro:
- Create a new Unity project and install the SteamVR Plugin 1.2.2
- Create a new scene
- Drag in the Steam [CameraRig] prefab
- Press PLAY
Expected:
- in VR headset can see my Vive Controllers
Actual:
- Can't see Vive controllers in VR, only in the editor scene window

Any ideas?

**Comment by peterept** [comment]
Further downgraded to Unity 2017.1 and still can't see the controllers in VR play.

**Comment by peterept** [comment]
Oh IGNORE ME! In turns out I had left the default Main Camera in the scene. That meant in VR I was seeing that camera and not the steam vr camera !!

**Comment by BenLorantfy** [comment]
I'm having the same issue as the OP. Any advice @bddckr ?

**Comment by BenLorantfy** [comment]
![wut](https://user-images.githubusercontent.com/4398635/29254006-94ffc970-8059-11e7-8567-e1b19939d1d0.png)

This is what happens when I launch the example scene and then hold the controllers infront of the headset,. They're not shown and they're grayed out in the inspector.

**Comment by BenLorantfy** [comment]
LOL never mind, my controllers were just in standby mode so they didn't show up.

**Comment by peterept** [comment]
LOL. Makes me feel less dumb about leaving the default Main Camera in my
scene when I couldnt see my controllers.:-)

**Comment by Sudarmin** [comment]
Same happening to me, my controllers are grayed out in unity editor, I'm using Oculus Touch, but the SteamVR home can detect my oculus touch, unity can't, I try shaking the controllers, pressing all the buttons, but no response

**Comment by pkarjala** [comment]
As a note, the current instructions in the quickstart.pdf included with the Steam VR plugin for setting this up state to add the `Steam VR_Camera` script to the existing Main Camera in the scene.  This causes the controllers to not correctly render.  Instead, as described, removing the Main Camera and then dragging the `[Camera Rig]` prefab into the scene causes the controllers to correctly render.

The PDF should be updated to reflect this, or the `Steam VR_Camera` script should be updated to correctly render the controllers if added to an existing camera in the scene.

**Comment by gevarre** [comment]
Same problems with 1.2.3 and at least windows 7. Even with a new project in any version of Unity from 5.6 to 2017.3 and just loading SteamVR's demo scene, the controllers don't show and the following errors show up:

Failed to load IVRRenderModels interface version IVRRenderModels_005
UnityEngine.Debug:LogError(Object)
RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:281)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

**Comment by grant-mullinax** [comment]
I am encountering an issue identical to the one above by @gevarre

**Comment by Benjaminhaesemeyer** [comment]
I am having the same issue as @gevarre

**Comment by jonthelin** [comment]
I am having the same issue as @gevarre in Unity 5.6.1p1, Windows 10, Vive headset and controllers, SteamVR 1.2.3

**Comment by SteveKrueger52** [comment]
I am having the same issue in Unity 2017.3.0f3 and SteamVR 1.2.3, and it is making it impossible to create the game we intended for the 2018 Global Game Jam

**Comment by davnkrit** [comment]
check out the fix I did for issue #66 "Cannot see Vive Controllers in VR with 1.2.3"...you may find it useful.

**Comment by gevarre** [comment]
Sorry, no. That doesn't fix anything.
Further info that may or may not help: After more testing, it seems to have something to do with the actual controller model. I now get this in the Unity console:

[Model] Render model does not support components, falling back to single mesh.
UnityEngine.Debug:Log(Object)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:285)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

Failed to load render model vr_controller_vive_1_5 - InvalidModel
UnityEngine.Debug:LogError(Object)
SteamVR_RenderModel:LoadRenderModel(CVRRenderModels, String, String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:332)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:300)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

**Comment by gevarre** [comment]
If I manually override the model in Unity, then it all works, though of course Unity (Valve's error message actually) complains that I shouldn't do this because it may not show up right for some users.

**Comment by bddckr** [comment]
I think this may actually be a SteamVR runtime bug or the render models in use (including the default one) on our PCs may be corrupted.

According to the last update to the Unity plugin there were only two changes to the RenderModel script:
https://github.com/ValveSoftware/steamvr_unity_plugin/commit/fad02abee8ed45791993e92e420b340f63940aca#diff-b12c770d638afe34828a513e3cdfcb46

None of which should result in this error:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/fad02abee8ed45791993e92e420b340f63940aca/Assets/SteamVR/Scripts/SteamVR_RenderModel.cs#L320-L334
As you can see the error is reported by OpenVR, so I'm not sure what the real issue here is.

---

All I know is it's working fine for some PCs while it doesn't work on others. All of them are using the default controller models. Every one of the PCs I tested with had SteamVR's tool files verified by Steam and a few of them even attempted SteamVR reinstallation without avail.

**Additional infos:**
If this issue occurs it occurs on the PC having the issue, no matter whether I run Unity builds of an app that using Unity 5.6, 2017.1, 2017.3 or SteamVR plugin version 1.2.2 or 1.2.3.

@aaronleiby @aleiby @JoeLudwig Sorry for pinging, but do you have any ideas what's going on here?

**Comment by gevarre** [comment]
I've talked to several vr devs in the Seattle area, and they seem to be having the same problem: If you leave things at their default, the models don't show up, if you manually override the model in unity (in the "Model Override" drop-down) to anything other than vr_controller_vive_1_5, the controllers show up and everything seems to work. I had just never noticed it before since I always make custom controller models.

These may or may not have anything to do with the actual problem, but here are the errors I'm now getting:

[Model] Render model does not support components, falling back to single mesh.
UnityEngine.Debug:Log(Object)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:285)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

Failed to load IVRRenderModels interface version IVRRenderModels_005
UnityEngine.Debug:LogError(Object)
RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
SteamVR_RenderModel:LoadComponents(RenderModelInterfaceHolder, String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:507)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:279)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

**Comment by kitdastudio** [comment]
@aleiby it worked ! 
the controller came back ! 
steamVR 1.2.3
unity 5.6.1f1
big THX !

**Comment by richardrevesz** [comment]
okay guys, with Unity 2017.1.1 and 2017.2.0f3 for me it works to downgrade to SteamVR 1.2.2 
(see commits under the code tab, browse files)
(VRTK 3.3.0)

**Comment by monkeymorgan** [comment]
updating SteamVR_Render.cs worked here with steamVR 1.2.3 and unity 5.5.0f3 (after much pain). First tried checking scene camera, swapping models, starting fresh scenes etc.

**Comment by Ayfel** [comment]
Same problem , after this script becomes deprecated the controllers don't show up. Had to roll back

**Comment by gevarre** [comment]
@ayfel: you don't mention which version of unity you are using, but if it's 2017, you can check out the other thread I mentioned where aleiby mentioned a fix by deleting your steamvr config folder:

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/66

Note: 2018 seems to now have other issues that this doesn't fix, so beware.

**Comment by Ayfel** [comment]
@gevarre You are right, sorry about that, I am using version 5.6.4p3. I will check that other thread now.

**Comment by smasish** [comment]
I am using 2018.3 but it does not work. Any help?
