### ISSUE TITLE
Make SteamVR Scripts Inheritable

### ISSUE THREAD

**Issue by ZnelArts** [ValveSoftware/steamvr_unity_plugin#563]
**As a developer I want to inherit SteamVR Interaction System scripts so that I can extend functionality without having to modify them**

Everybody knows that modifying 3rd party libraries is no good, if we do then we will eventually update them and lose all the edits we have made to them.
One could say we rewrite our own scripts copying the library script and making our edits on our custom script. This is not scalable because once there is a mayor refactor our script could become unusable, buggy or incompilable.

The solution is to make scripts on the interaction system that are friendly to be inherited, with this we can leverage the native SteamVR functionality and only override or overwrite certain functions in which we want to change the functionality.

How can you make SteamVR inheritable scripts:

- Make all private members to be **protected**
- Mark all functions as **virtual**

see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/inheritance

**Comment by zite** [comment]
Unfortunately this interaction system is not meant as a base for other systems to be built on top of and maintained. It's meant more as an example for how to implement your own system. Because of that we do occasionally break backwards compatibility by changing how something works or removing methods / scripts all together. 

If you do want to build on top of this system we'd recommend doing what you suggested and copying it out of the steamvr folder. But, like you say, you'd be in charge of maintaining it.
