### ISSUE TITLE
Steam VR_Skeleton_Poser rotating the vr_glove ... (Clone) causes the glove to stretch out of proportion

### ISSUE THREAD

**Issue by TRAILtheGREAT** [ValveSoftware/steamvr_unity_plugin#736]
rotating vr_glove_right_model_slim(Clone) around the x axis causes the model to stretch out of proportion, however the stretching disappears in the game. this makes it impossible to arrange the skeleton because the model that I'm editing doesn't match the model in game.
default skeleton:
![image](https://user-images.githubusercontent.com/55848180/82747484-fc59af00-9d4d-11ea-8c16-f4bc1ba82fef.png)
after rotating 65 degrees about the x axis:
![image](https://user-images.githubusercontent.com/55848180/82747489-14313300-9d4e-11ea-80de-bf41451ac8b4.png)

**Comment by TRAILtheGREAT** [comment]
upon further experimentation, it appears that the hand scales with the game object it is attached to, so if the game object does not have equal scale in all directions, the hand will stretch when rotated.

**Comment by flightCrazed** [comment]
This is expected behavior in Unity all transforms. I like to keep the root unscaled (1,1,1) for this reason and child objects are the ones that would be scaled. So I can attach the hand to the root and it won't be scaled. There is no way around this unless you un-parent and re-parent every time you change the scale.

**Comment by TRAILtheGREAT** [comment]
thank you for your patience. I'll see myself out
