### ISSUE TITLE
HTC Vive Controller Invisible in Unity

### ISSUE THREAD

**Issue by CSDevHarris** [ValveSoftware/steamvr_unity_plugin#891]
This is similar to many posts on various forums, but it doesn't have exactly the same configuration or symptoms (and I've tried a lot of the workarounds).

When setting up SteamVR in the configuration below, I can see the hands and perform user actions via the controllers (teleport, grab, menu, etc.), but I can't see the controllers. Interestingly, I see the controllers for a split second on game start, and I can see the transparent controllers when button hints are flashing.

Unity 2020.2.1f1
SteamVR Plugin 2.7.1
SteamVR Runtime 1.13.9
Project Type: Basic 3D, URP, or HDRP (I know, not supported, but worth a shot)
Using the [Player] prefab

I know this is all bleeding edge configuration, so I understand that there be dragons, but I'd like to dig into Unity 2020.2 (or something close) and use a version of SteamVR with support for the "new" XR Plug-In Management and URP-friendly interactions/materials. In other words, use URP (and eventually HDRP) with SteamVR.

One common comment with similar issues is the requirement to have Steam running.
- #412
- [https://forum.unity.com/threads/htc-vive-controller-not-working-in-unity.872026/](https://forum.unity.com/threads/htc-vive-controller-not-working-in-unity.872026/)

If that's the core problem, I'm stuck, as I'm in an enterprise closed environment with no ability to connect to Steam.
It would be nice to know for sure.

I'm all ears for any other thoughts or suggestions.
Thank you!

**Comment by AlkalineDevelopment** [comment]
As far as I'm aware the controllers don't show by default. Since your using the player prefab select either the Left or Right-hand GameObject and near the bottom of the Hand script it should say "Render Model Prefab" select the referenced GameObject and it should pull up that controllers prefab with a Render Model script. From there you can toggle if it shows the Hand or Controller by default or both.

You can also toggle showing the controller via methods in the Hand script called ShowController() and HideController()

**Comment by CSDevHarris** [comment]
Well well well.
Thank so much. I was accustomed to a much older version of the plug-in. The behavior's a bit different, and I thought something was squirrelly with the overall configuration.
Onward and upward. Thank you!
