### ISSUE TITLE
OpenVRSettings.asset exported by Unity as a BINARY file instead of a TXT file

### ISSUE THREAD

**Issue by RaveTZ** [ValveSoftware/steamvr_unity_plugin#909]
SOLVED:  Original issue listed below.

The issue is that Unity was exporting OpenVRSettings.asset as BINARY and not TXT.  We hand edited a TXT version and manually placed it in the build and it worked.  Edits to the exporter should probably be made.

ORIGINAL POST -------

The **Player.log** is filled with
[XR] [OpenVR] [Error] Unsupported application type: 0
[XR] [OpenVR] [Error] Unable to submit eye texture: [103]

I've been struggling to get anything to render in a SteamVR build.  _It runs great in Editor._

All I see in build is the default SteamVR grid with mountains in the distance.

I've double checked that my actions.json and binding files are in place, that my OpenVRSettings.asset is in \StreamingAssets\SteamVR\ and that my launch settings in Steamworks is set to SteamVR App

My Open VR Settings is set to App Type Scene, Multi Pass, Mirror Type None, Left, Right and OpenVR (all tested individually)

This is a windows x64 build using:  OpenVR XR Plugin 1.1.4
Unity3D 2019.4.17f
XR Legacy Input Helpers 2.16
XR Plugin Management 3.2.16

[Player.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/5943081/Player.log)

**Comment by matt-bcs** [comment]
You need to change unity assets to text instead of binary.  After that the exporter will copy over a text version OpenVRSettings.asset

**Comment by ZnelArts** [comment]
I am also experiencing this issue, has anybody found a fix? I cannot set the project to force text serialization because it makes Cloud Builds take over 40 hours each time

**Comment by GarrettCMiller** [comment]
This must be the problem I'm having too. Runs just fine in the editor but builds give me errors and don't display anything. I'm a little irritated because the last two times I tried to tell Unity to force text serialization, it ran for over 50 hours and never recovered. So both times I had to force close the app and when I re-open, it's still stuck in mixed mode. Does ANYONE know how I can force it to export a text OpenVRSettings.asset without locking the whole program for multiple days just for it to never recover and be force closed, completely wasting those days? Or can someone tell me where to find an example OpenVRSettings.asset text file and what I need to change for my project?

**Comment by zite** [comment]
As a temporary solution you can use the beta release here: https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.5b
Otherwise a fix will come with the next version of this plugin.

**Comment by Peri995** [comment]
> SOLVED: Original issue listed below.
> 
> The issue is that Unity was exporting OpenVRSettings.asset as BINARY and not TXT. We hand edited a TXT version and manually placed it in the build and it worked. Edits to the exporter should probably be made.
> 
> ORIGINAL POST -------
> 
> The **Player.log** is filled with [XR] [OpenVR] [Error] Unsupported application type: 0 [XR] [OpenVR] [Error] Unable to submit eye texture: [103]
> 
> I've been struggling to get anything to render in a SteamVR build. _It runs great in Editor._
> 
> All I see in build is the default SteamVR grid with mountains in the distance.
> 
> I've double checked that my actions.json and binding files are in place, that my OpenVRSettings.asset is in \StreamingAssets\SteamVR\ and that my launch settings in Steamworks is set to SteamVR App
> 
> My Open VR Settings is set to App Type Scene, Multi Pass, Mirror Type None, Left, Right and OpenVR (all tested individually)
> 
> This is a windows x64 build using: OpenVR XR Plugin 1.1.4 Unity3D 2019.4.17f XR Legacy Input Helpers 2.16 XR Plugin Management 3.2.16
> 
> [Player.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/5943081/Player.log)

I am having exact same problem as OP.
I changed all StreamingAssets from .json to .txt, double checked that it worked in Editor. Changed in the OpenVRSettings to use actions.txt instead of actions.json, although you guys didn't have to do that.

In build, .txt files are exported, but the application doesn't work. It gives the same error.

Can you guys send me your OpenVRSettings.asset so that it's made for .txt?
Or any other additional help will be greatly appreciated. I will give you more info if you need it

Thanks anyways, regards,
Peri_95

**Comment by guiglass** [comment]
Where do I find OpenVRSettings.asset file? I have searched entire project, search github, searched internet, there is no mention of the file's location?
