### ISSUE TITLE
Rigidbody with collider tracked to head?

### ISSUE THREAD

**Issue by jmwhyte2002** [ValveSoftware/steamvr_unity_plugin#914]
Does anyone know how to have a rigidbody with a capsule collider placed directly under the camera / player head?
I've tried using the bodycollider object in the player prefab, however this doesn't work when gravity comes into effect as it isn't a parent of the rest of the rig.
Naturally, the next thing to try is adding the rigidbody and collider as a component of the player prefab parent rather than the bodycollider object. However, this results in an offset with the capsule collider, I have no idea what's causing it. It's in place if the headset is in dead center of the playspace. However, as you move outwards, the collider follows but at a much slower rate, so by the time you move a metre or so you have become completely detached from it.
Please help, I'm driving myself crazy trying to figure out what's wrong here.

**Comment by troyspencer** [comment]
I worked through this while building my game. I believe all that's needed for this configuration is 
- RigidBody attached to the top level Player prefab (and remove the existing one that's attached to the BodyCollider)
- CapsuleCollider attached to the BodyCollider (which will update its own position to be underneath the head due to the BodyCollider script)

**Comment by zite** [comment]
This isn't really the correct forum for questions like this. Please see: https://steamcommunity.com/app/250820/discussions/7/
